import re

FILENAME = "HPatPS.txt"

def main():
    passphrase = "I solemnly swear that I am up to no good."
    phrase = ""
    escape = "escape"
    
    while (phrase != passphrase):
        print(passphrase)
        print("Type the passphrase above to continue...")
        phrase = input(">>> ")
        if (phrase == escape):
            return
        if ((phrase == "F") or (phrase == "f")):
            print("Paying your respects, I see.")
        if (phrase != passphrase):
            print("Incorrect passphrase. Try again.")
    
    print("Transmogrifying text...", end = "\n\n")
    file = open(FILENAME, "r")
    text = file.read()
    file.close()

    text = transmogrify(text)
    print(text, end = "\n\n")
    
    file = open("transmogrified-" + FILENAME, "w")
    file.write(text)
    file.close()
    
    print("Mischief Managed.")

def replace(text, word, replacement):
    return re.sub(word, replacement, text, flags = re.IGNORECASE)

def transmogrify(text):
    text = replace(text, "By J.K. Rowling", "Author: J.K. Rowling\nEdited By The")
    text = replace(text, "boy", "Baby Villager")
    text = replace(text, "Dursley", "Stone")
    text = replace(text, "Privet", "Cobblestone")
    text = replace(text, "young people", "Baby Villagers")
    text = replace(text, "people", "Villagers")
    text = replace(text, "nonsense", "Andesite")
    text = replace(text, "Grunnings", "Mojang")
    text = replace(text, "Drill", "Hopper")
    text = replace(text, "man", "Villager")
    text = replace(text, "neck", "Netherite")
    text = replace(text, "moustache", "Log")
    text = replace(text, "blonde", "Spongy")
    text = replace(text, "garden fence", "Wooden Fence")
    text = replace(text, "neighbour", "Villager")
    text = replace(text, "Dudley", "Alex")
    text = replace(text, "a secret", "Diamond")
    text = replace(text, "Potters", "Diamonds")
    text = replace(text, "sister", "Female Villager")
    text = replace(text, "husband", "Male Villager")
    text = replace(text, "in the street", "on their Doorstep")
    text = replace(text, "child", "Baby Villager")
    text = replace(text, "Tuesday", "Furnace")
    text = replace(text, "country", "Overworld")
    text = replace(text, " tie", " Music Disc")
    text = replace(text, "into his high chair", "onto his Illager Throne")
    text = replace(text, " owl", " Cake")
    text = replace(text, "owls", "Cakes")
    text = replace(text, "window", "Stained Glass Window")
    text = replace(text, "briefcase", "Ender Chest")
    text = replace(text, "cereal", "Mushroom Stew")
    text = replace(text, "tyke", "Baby Bee")
    text = replace(text, "House", "Woodland Mansion")
    text = replace(text, " Car ", " Minecart ")
    text = replace(text, "a Cat", "an Ocelot")
    text = replace(text, "cat", "Ocelot")
    text = replace(text, "Map", "Map")
    text = replace(text, "head", "Mob Head")
    text = replace(text, "overMob Head", "overhead")
    text = replace(text, "in broad daylight", "the Daylight Sensor")
    text = replace(text, "silver cigarette lighter", "Flint and Steel")
    text = replace(text, "Put-Outer", "Flint and Steel")
    text = replace(text, " light", " Redstone Torch")
    text = replace(text, "road", "Cobblestone road")
    text = replace(text, "mirror", "Iron Ingot")
    text = replace(text, "sign", "Wooden Sign")
    text = replace(text, "mind", "Mob Head")
    text = replace(text, "town", "the NPC Village")
    text = replace(text, "cloak", "Cape")
    text = replace(text, "clothes", "Capes")
    text = replace(text, "steering wheel", "edge of the Minecart")
    text = replace(text, "eye", "Eye of Ender")
    text = replace(text, "Eye of Enders", "Eyes of Ender")
    text = replace(text, "weirdos", "Pillagers")
    text = replace(text, "Emerald", "Emerald")
    text = replace(text, "nerve", "Redstone-Wire")
    text = replace(text, "for something", "Gold")
    text = replace(text, "waiting Gold", "waiting for something")
    text = replace(text, "telephone calls", "Redstone telegrams")
    text = replace(text, "bun", "piece of Bread")
    text = replace(text, "Eye of Enderd them \nangrily", "stared angrily at them with his Eye of Ender")
    text = replace(text, "collecting tin", "Shulker Box")
    text = replace(text, "doughnut", "Music Disc")
    text = replace(text, "Fear", "Lava")
    text = replace(text, "greatest Lava", "greatest fear")
    text = replace(text, "office", "Command Block")
    text = replace(text, "telephone", "Redstone Dust")
    text = replace(text, "receiver", "Repeater")
    text = replace(text, "secretary", "Witch")
    text = replace(text, "clock", "Clock")
    text = replace(text, "someone", "a Villager")
    text = replace(text, " door", " Door")
    text = replace(text, "to the ground", "into the Flowing Water")
    text = replace(text, "squeaky", "Villager's")
    text = replace(text, "stranger", "Illager")
    text = replace(text, "driveway", "Cobblestone driveway")
    text = replace(text, "garden wall", "Wooden Fence")
    text = replace(text, "wife", "Female Villager")
    text = replace(text, " bed", " Bed")
    text = replace(text, "Ocelotch", "catch")
    text = replace(text, "birds", "Cakes")
    text = replace(text, "Jim", "Steve")
    text = replace(text, " Ted", " Steve")
    text = replace(text, "Kent", "the NPC Village")
    text = replace(text, "Yorkshire", "the NPC Village")
    text = replace(text, "Dundee", "the NPC Village")
    text = replace(text, "phoning", "telegraphing")
    text = replace(text, "rain", "Downfall")
    text = replace(text, "stars", "Nether Stars")
    text = replace(text, "Bonfire", "Campfire")
    text = replace(text, "Britain", "the Overworld")
    text = replace(text, "Minecartrying", "carrying")
    text = replace(text, "Minecart Door", "Minecart")
    text = replace(text, "cups of tea", "Buckets of Water")
    text = replace(text, " tea", " Still Water")
    text = replace(text, "Diamonds knew", "Potters knew")
    text = replace(text, "no Wooden Sign", "sign")
    text = replace(text, "a statue", "an Armour Stand")
    text = replace(text, "ground", "Dirt")
    text = replace(text, "boots", "Gold Boots")
    text = replace(text, "street lamp", "Redstone Lamp")
    text = replace(text, "You-Know-Who", "the Arch-Illager")
    text = replace(text, "You-Know", "the-Arch")
    text = replace(text, " lamp", " Torch")
    text = replace(text, "Enderd", "Endered")
    text = replace(text, "pavement", "Stone Slabs")
    text = replace(text, "woVillager", "Witch")
    text = replace(text, "brick", "Brick")
    text = replace(text, "sherbet", "Golden")
    text = replace(text, "lemon", "Nugget")
    text = replace(text, "earmuffs", "Turtle Shell")
    text = replace(text, "Diamonds'", "Potters'")
    text = replace(text, "heaven", "Herobrine")
    text = replace(text, "handkerchief", "piece of Wool")
    text = replace(text, "letter", "Book and Quill")
    text = replace(text, "glasses", "spectacles")
    text = replace(text, "heart", "Heart Of The Sea")
    text = replace(text, "some Wooden Sign of a Mob Headlight", "any sign of Hostile Mobs")
    text = replace(text, "motorbike", "Elytra")
    text = replace(text, "climbing carefully", "taking")
    text = replace(text, "Drowned out", "fell out")
    text = replace(text, "leather Gold Boots", "Leather Boots")
    text = replace(text, "baby", "Baby")
    text = replace(text, "Baby Baby", "Baby")
    text = replace(text, "dolphins", "Dolphins")
    text = replace(text, "piece of Breaddle", "bundle")
    text = replace(text, "Bristol", "NPC Village")
    text = replace(text, "foreMob Head", "forehead")
    text = replace(text, " dog", " Wolf")
    text = replace(text, "bike ", "Elytra ")
    text = replace(text, "jacket sleeve", "Leather Tunic")
    text = replace(text, "engine", "Elytra")
    text = replace(text, "balls of Redstone Torch", "Firecharges")
    text = replace(text, "Redstone Torchs", "Redstone Lamps")
    text = replace(text, "milk bottles", "Buckets of Milk")
    text = replace(text, "over NPC Village", "overhead")
    text = replace(text, "Redstone Torchning", "Lightning")
    return text

if (__name__ == "__main__"):
    main()
